---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: kpm
  name: kpm
spec:
  type: {{svc_type}}
  ports:
    - port: 80
      targetPort: 5000
      name: kpm
  selector:
    k8s-app: kpm
