sudo: false

addons:
  code_climate:
    repo_token: a6adb14185da38fc06b3df732a5b2a5cc06df0004f73b2a792c10b3d5fdbe3ff

env:
  - TOXENV=coveralls
  - TOXENV=flake8

install: pip install -U tox
language: python
script: tox

after_success:
  - coveralls